### PR TITLE
API improvements

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by wcandillon** [comment]
@rdougan  this new version should address your issue.

**Comment by rdougan** [comment]
Thanks! Let me know when it is released please.

**Comment by wcandillon** [comment]
@rdougan This is published in `1.3.1`, can you let me know if this works for you? You can use `headers` property in `source`. Keep me posted.

**Comment by rdougan** [comment]
@wcandillon it works, thanks!

**Comment by wcandillon** [comment]
cool :)

**Pull request merged**
