### PR TITLE
According to the example this.props.uri is undefined

### PR DESCRIPTION
**Pull request by jarandmi**
this.props.source.uri should be the correct path to get the Uri. I also corrected the npm package from react-native-image-cache (thats another package) to react-native-img-cache

### CODE REVIEW

**Comment by wcandillon** [comment]
@jarandmi Thks for correcting the readme! Could you make it in a separate PR and I will merge it immediately. Regarding the change in `index.ts`, could you elaborate? It seems to cause a regression on existing code.

**Review by wcandillon — CHANGES_REQUESTED** [review]
Thks for correcting the readme! Could you make it in a separate PR and I will merge it immediately. Regarding the change in index.ts, could you elaborate? It seems to cause a regression on existing code.

**Comment by wcandillon** [comment]
@jarandmi This is the readme example that is broken, I will fix it thks!

**Comment by wcandillon** [comment]
@jarandmi Closing for now, feel free to re-open.

**Comment by jarandmi** [comment]
@wcandillon  I would still prefer to use the same syntax as the official <Image / > component. `<Image source={ uri: http://.../image.jpg} / >`. Then all you have to do to change the component name. Now you also have to change the props.

**Comment by wcandillon** [comment]
@jarandmi my issue with using source is that people might do:
```jsx
<CachedImage source={require("./Image.jpg")} />
```
Which wouldn't work. Maybe `CachedImage` should have a pass through for images it doesn't need to cache. What are your thoughts on this?

**Comment by jarandmi** [comment]
I see. Yeah, a pass trough would probably be a good idea. 
`<Image { ...props } />` would probably solve that?

**Pull request closed without merging**
